#!/bin/bash
# release-upgrade - Upgrade nodes to the next stable Debian/Raspbian version
#    Copyright (C) 2017  Jeremy Lincicome (W0JRL)
#    https://jlappliedtechnologies.com  admin@jlappliedtechnologies.com

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Script Start
# functions
prompt() {
echo "${name} ${release} is abailable."
read -e -p "do you wish to upgrade? [Y/N]" upgrade
if [[ "$upgrade" = "y" ]] || [[ "$upgrade" = "Y" ]]; then
  echo "Upgrading to ${name} ${release}
This is going to take a while.
Do *NOT* power off the system!"
else
  echo "Not upgrading to ${name} ${release}.
Run 'release-upgrade' when you are ready."
  exit 1
fi
}
distro() {
platform=$(lsb_release -is)
if [[ $platform = "Raspbian" ]]; then
  name=RasLink
else
  name=RasLink-PC
fi
prev=jessie
release=stretch
}
check() {
if [[ $(grep "${release}" /etc/apt/sources.list) != "0" ]]; then
  exit 0
fi
}
update() {
sed -i "s/${prev}/${release}/" /etc/apt/sources.list /etc/apt/sources.list.d*.list
(apt-get update;yes | apt-get dist-upgrade)
cd /root
mv .bashrc .bashrc.orig
cat .bashrc.orig > .bashrc
if [[ $platform = "Raspbian" ]]; then
  echo "/usr/src/utils/AllStar-build/rpi/update-stage2.sh" >> .bashrc
else
  echo "/usr/src/utils/AllStar-build/debian/update-stage2.sh" >> .bashrc
fi
sed -i '/PermitRootLogin/c\PermitRootLogin yes/' /etc/ssh/sshd_config
echo "Rebooting to finish install"
echo "When your node reboots, you need to log in
to finish the upgrade."
sync
sudo reboot
}
# Run the upgrade
distro
check
prompt
update
exit 0
